# Generated by Django 5.2.6 on 2025-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=50)),
                ('released', models.DateField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
